version: 2.1

executors:
  default:
    machine:
      image: circleci/classic:edge

orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build

  test:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: docker-compose up -d
          command: docker-compose up -d
      - run: sleep 10
      - run:
          name: docker-compose exec web bundle exec rails db:create RAILS_ENV=development
          command: docker-compose exec web bundle exec rails db:create RAILS_ENV=development
      - run:
          name: docker-compose exec web bundle exec rails db:migrate RAILS_ENV=development
          command: docker-compose exec web bundle exec rails db:migrate RAILS_ENV=development
      - run:
          name: docker-compose exec web bundle exec rubocop 
          command: docker-compose exec web bundle exec rubocop 
      - run:
          name: docker-compose exec web bundle exec rspec -f d spec/models/user_spec.rb
          command: docker-compose exec web bundle exec rspec -f d spec/models/user_spec.rb

  deploy:
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run: 
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  build_test_deploy:
   jobs:
    - build
    - test:
        requires:
          - build
    - deploy:
        requires:
          - test
        filters:
          branches:
            only: main