version: 2.1 

executors: 
  default_ruby:
    docker:
      - image: circleci/ruby:3.0.0
        environment: 
          RAILS_ENV: test
          APP_DATABASE_HOST: "127.0.0.1"

  default_mysql:
    docker:
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: user  


commands: 
  restore_Gemfile:
    steps:
      - restore_cache:
          name: Restore Gemfile dependencies
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  save_Gemfile:
    steps:
      - save_cache:
          name: Cache Gemfile dependencies
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

orbs: 
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs: 
  build_test:
    executor:
      name: default_ruby
    working_directory: ~/portfolios-museum/src
    steps:
        - checkout:
            path: ~/portfolios-museum
        - restore_Gemfile
        - run: bundle config set deployment 'true'
        - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
        - save_Gemfile
        - run:
            name: Rubocop
            command: bundle exec rubocop
        - run:
            name: Rspec
            command: bundle exec rspec
  
  deploy:
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run: 
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME
    
workflow: 
  build_test&deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: main