workflows:
  version: 2
  build_rubocop_deploy:
   jobs:
    - build
    - rubocop:
        requires:
          - build
    - deploy:
        requires:
          - rubocop
        filters:
          branches:
            only: master


version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
    working_directory: ~/portfolios-museum/src
    steps:
      - checkout:
          path: ~/portfolios-museum
      - ruby/install-deps
  
  rubocop:
    docker:
      - image: circleci/ruby:3.0.0
        environment: 
          RAILS_ENV: test
          APP_DATABASE_HOST: "127.0.0.1"
      - image: cicleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root  
    working_directory: ~/portfolios-museum/src
    steps:
      - checkout:
          path: ~/portfolios-museum
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Rubocop
          command: bundle exec rubocop
          
  
  deploy:
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run: 
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME